Simplification and issues fixed with score-k8s 0.3.2
Signed-off-by: Mathieu Benoit <mathieu-benoit@hotmail.fr>

diff --git a/score-k8s/10-redis-helm-upgrade.provisioners.yaml b/score-k8s/10-redis-helm-upgrade.provisioners.yaml
--- a/score-k8s/10-redis-helm-upgrade.provisioners.yaml
+++ b/score-k8s/10-redis-helm-upgrade.provisioners.yaml
@@ -4,14 +4,13 @@
   - -c
   - |
     if [ -z "$NAMESPACE" ]; then
-      echo "Error: The NAMESPACE environment variable shouldn't be empty. That's where the Redis Helm chart will be installed." >&2
+      echo "Error: The NAMESPACE environment variable shouldn't be empty. That's where the Redis Helm chart will be installed with this provisioner." >&2
       exit 1
     fi
     STDIN=$(cat)
-    SERVICE=$(echo $STDIN | yq eval -p json '.resource_id' | yq '. |= sub("\.", "")' | yq '. |= sub("-", "")')
+    SERVICE=$(echo $STDIN | yq eval -p json '.resource_id' | yq '. |= sub("\.", "-")')
     set -eu -o pipefail
     helm repo add bitnami https://charts.bitnami.com/bitnami >&2
     helm upgrade -i ${SERVICE} bitnami/redis --set replica.replicaCount=1 -n ${NAMESPACE} --wait >&2
-    PASSWORD_REFERENCE=$(echo ${SERVICE} | base64).$(echo redis-password | base64)
-    OUTPUTS='{"resource_outputs":{"host":"%s-master", "port":"6379", "username":"", "password":"🔐💬%s💬🔐"},"manifests":[]}'
-    printf "$OUTPUTS" "$SERVICE" "$PASSWORD_REFERENCE"
+    OUTPUTS='{"resource_outputs":{"host":"%s-master", "port":"6379", "username":"", "password":"🔐💬%s_redis-password💬🔐"},"manifests":[]}'
+    printf "$OUTPUTS" "$SERVICE" "$SERVICE"
