Bitnami Helm chart generate the namespace field in the rendered manifests by helm template, we need to supply the actual namespace name as input of the redis-helm-template provisioner
Signed-off-by: Mathieu Benoit <mathieu-benoit@hotmail.fr>

diff --git a/score-k8s/10-redis-helm-template.provisioners.yaml b/score-k8s/10-redis-helm-template.provisioners.yaml
--- a/score-k8s/10-redis-helm-template.provisioners.yaml
+++ b/score-k8s/10-redis-helm-template.provisioners.yaml
@@ -3,6 +3,10 @@
   args:
   - -c
   - |
+    if [ -z "$NAMESPACE" ]; then
+      echo "Error: The NAMESPACE environment variable shouldn't be empty. It's used in the Kubernetes manifests generated by this provisioner from the Redis Helm chart." >&2
+      exit 1
+    fi
     STDIN=$(cat)
     SERVICE=$(echo $STDIN | yq eval -p json '.resource_id' | yq '. |= sub("\.", "-")')
     set -eu -o pipefail
