stderr if no namespace
Signed-off-by: Mathieu Benoit <mathieu-benoit@hotmail.fr>

diff --git a/score-k8s/10-redis-helm-upgrade.provisioners.yaml b/score-k8s/10-redis-helm-upgrade.provisioners.yaml
--- a/score-k8s/10-redis-helm-upgrade.provisioners.yaml
+++ b/score-k8s/10-redis-helm-upgrade.provisioners.yaml
@@ -4,7 +4,7 @@
   - -c
   - |
     if [ -z "$NAMESPACE" ]; then
-      echo "The NAMESPACE environment variable shouldn't be empty. That's where the Redis Helm chart will be installed."
+      echo "Error: The NAMESPACE environment variable shouldn't be empty. That's where the Redis Helm chart will be installed." >&2
       exit 1
     fi
     helm repo add bitnami https://charts.bitnami.com/bitnami > helm-logs.txt
